# Generated by Django 5.0 on 2024-10-18 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appFT', '0002_fitnessplan_gymmember'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gymmember',
            name='joined_date',
        ),
        migrations.AlterField(
            model_name='gymmember',
            name='trainer',
            field=models.CharField(blank=True, choices=[('trainer_1', 'Тренер 1'), ('trainer_2', 'Тренер 2'), ('trainer_3', 'Тренер 3')], max_length=50, null=True),
        ),
    ]
