# Generated by Django 5.0 on 2024-10-18 12:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appFT', '0003_remove_gymmember_joined_date_alter_gymmember_trainer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gymmember',
            name='trainer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='appFT.trainer'),
        ),
    ]
