# Generated by Django 5.0 on 2024-10-18 12:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appFT', '0004_alter_gymmember_trainer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gymmember',
            name='plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appFT.plan'),
        ),
        migrations.AddField(
            model_name='plan',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.DeleteModel(
            name='FitnessPlan',
        ),
    ]
