# Generated by Django 5.0 on 2024-10-18 12:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appFT', '0005_alter_gymmember_plan_plan_price_delete_fitnessplan'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrainingSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('duration', models.PositiveIntegerField()),
                ('notes', models.TextField(blank=True, null=True)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appFT.gymmember')),
                ('trainer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appFT.trainer')),
            ],
        ),
    ]
