# Generated by Django 4.2.16 on 2024-10-23 12:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('appFT', '0007_gymmember_profile_image_gymmember_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gymmember',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='gymmember',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='gym_member', to=settings.AUTH_USER_MODEL),
        ),
    ]
