# Generated by Django 5.0.2 on 2024-10-25 18:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appFT', '0008_alter_gymmember_email_alter_gymmember_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='gymmember',
            name='additional_info',
            field=models.TextField(blank=True, default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='gymmember',
            name='plan',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='appFT.plan'),
        ),
        migrations.AlterField(
            model_name='gymmember',
            name='profile_image',
            field=models.ImageField(default='default_image.png', upload_to='profile_images/'),
        ),
        migrations.AlterField(
            model_name='gymmember',
            name='trainer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='appFT.trainer'),
        ),
        migrations.AlterField(
            model_name='gymmember',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
