# Generated by Django 5.0.2 on 2024-10-25 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appFT', '0009_alter_gymmember_additional_info_alter_gymmember_plan_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gymmember',
            name='additional_info',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='gymmember',
            name='profile_image',
            field=models.ImageField(default='default_avatar.png', upload_to='profile_images'),
        ),
    ]
