# Generated by Django 5.0.2 on 2024-10-25 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appFT', '0010_alter_gymmember_additional_info_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gymmember',
            name='profile_image',
            field=models.ImageField(default='default_avatar.jpg', upload_to='profile_images'),
        ),
    ]
