# Generated by Django 5.0.2 on 2024-10-25 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appFT', '0016_alter_gymmember_profile_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='training_days',
            field=models.JSONField(default=list),
        ),
    ]
