# Generated by Django 5.0.2 on 2024-10-25 20:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appFT', '0017_plan_training_days'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainingsession',
            name='plan',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='appFT.plan'),
            preserve_default=False,
        ),
    ]
