# Generated by Django 5.0.2 on 2024-10-26 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appFT', '0019_alter_gymmember_profile_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainingsession',
            name='completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='trainingsession',
            name='exercises',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='trainingsession',
            name='reps',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='trainingsession',
            name='sets',
            field=models.IntegerField(default=0),
        ),
    ]
