# Generated by Django 5.1.2 on 2024-10-28 10:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appFT', '0020_trainingsession_completed_trainingsession_exercises_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trainingsession',
            name='completed',
        ),
        migrations.RemoveField(
            model_name='trainingsession',
            name='exercises',
        ),
        migrations.RemoveField(
            model_name='trainingsession',
            name='reps',
        ),
        migrations.RemoveField(
            model_name='trainingsession',
            name='sets',
        ),
    ]
